### PR TITLE
MullVad VPN integration and Python2 compatibility for Captcha solving

### PR DESCRIPTION
**Pull request by mikvrax**
Added:
mullvad
custom gateway for mullvad 
cmdline option for mullvad
unit test for mullvad
all of the above are python2 compatible
python2 compatibility for captchasolver and its unit test

### CODE REVIEW

**Comment by devos50** [comment]
ok to test

**Comment by devos50** [comment]
@mikvrax please let me know when it's ready.

**Comment by mikvrax** [comment]
It is ready

**Comment by Jaapp-** [comment]
Closing this because it has been merged in #58

**Pull request closed without merging**
